DEPENDENCIES: {}

GUILD_ID: 123

DEVELOPERS: []

TOURNAMENT:
  TRIGGER_CHANNELS:
    [
      { "ID": 1329728515070889994, "TYPE": 2 },
      { "ID": 1329728534779924541, "TYPE": 3 },
    ]

NAME_ROLES: {}
LEGACY_ROLES: []

SIX_MAN:
  CATEGORY: 1274657428645871662
