services:
  # SCUFFBOT
  bot:
    build: ./
    restart: unless-stopped
    volumes:
      - ./.local-secrets:/secrets
      - ./config.yaml.local:/config/config.yaml.local
    env_file:
      - ./.env.local
