name: Build and push to Docker Hub

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and push to Docker Hub
    runs-on: arc-runner-set
    steps:
      - name: Determine Environment
        id: set-environment
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          else
            echo "env=dev" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_EVENT_NAME: ${{ github.event_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ORG_DOCKERHUB_USERNAME }}
          password: ${{ secrets.ORG_DOCKERHUB_TOKEN }}

      - name: Extract repository name
        id: extractor
        run: |
          echo "${{ github.repository }}" | sed -E "s|^.*/(.*)$|repo_name=\1|" | tr "[:upper:]" "[:lower:]" >> $GITHUB_OUTPUT

      - name: Build and push to ${{ steps.set-environment.outputs.env }}
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.ORG_DOCKERHUB_USERNAME }}/${{ secrets.ORG_DOCKERHUB_REPO }}:${{ steps.extractor.outputs.repo_name }}-${{ steps.set-environment.outputs.env }}
